### ISSUE TITLE
Clearing caches fails

### ISSUE THREAD

**Issue by Hobokens** [sypets/brofix#37]
TYPO3 10.4.15
When brofix is installed the clearing caches fails.

---------------

Thanks for the helpful extension.

**Comment by sypets** [comment]
I can't reproduce the problem with TYPO3 10.4.15 and brofix 1.0.2, page_callouts 1.0.2

**Comment by Hobokens** [comment]
I'm using brofix 1.04., page_callouts 1.0.4.
I'm sorry , I don't get any error messages in the browser console or in `typo3temp/var/logs or var/log`.

**Comment by sypets** [comment]
Do you see an error message or how do you know the cache fails? How do you clear cache (e.g. via Maintenance > Flush Cache)?

Sorry about the multiple questions - I haven't been able to reproduce this and I do not have an idea at the moment, what might cause this problem. Any additional information might be helpful to narrow it down. Apart from the automatic tests, I usually use the extension on multiple systems (production and development), however I am currently making more changes rapidly, so the latest versions have not been  tested as much as the previous versions. If I track down the problem, I will let you know and fix it.

**Comment by Hobokens** [comment]
Fortunately, after deleting the entire temp directory on the server, the error has just disappeared.
I'm sorry to have troubled you with the question. 
Thank you for the development of the extension. It noticeably increases the convenience of checking links. 
The only problem I have now is that many external links are displayed as broken, although they work in the browser. But you already noted that as an issue.

**Comment by sypets** [comment]
@Hobokens You might want to update the extension (>= 1.0.6). I recently fixed a problem in Services.yaml. I saw an error related to that once but have not been able to reproduce. I am not sure, but this might be related to your problem.

Thank for the report - it is important for me to get feedback, so no trouble.

On the master branch, I am working on further changes, next version will 2.0.0 (with support for only TYPO3 10).

About the external links that are displayed as broken, but work (false positives) - I think excluding specific URLs (and domains) is a good approach, because I do not think it will be possible to solve all the problems with optimizing the HTTP requests (though this should be looked at as well). It is currently already possible to exclude specific URLs (and domains) with the "exclude" button:

![image](https://user-images.githubusercontent.com/13206455/118229149-ca27ec80-b48b-11eb-889d-b7cdd3ff4b0a.png)

This can be made available to editors as well by configuration: https://docs.typo3.org/p/sypets/brofix/1.0/en-us/Setup/Quickstart.html

You might want to be restrictive with that though, I saw editors exclude working URLs and I think the workflow is yet to be improved but still it is better than having working URLs marked as broken.

I do think there is still room for optimization of the workflow / usability with the "exclude" button. 

Feel free to make suggestions in the other issues.
